version: '3.8'

services:
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./comunicacao-ms/.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./comunicacao-ms/.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  servico_a:
    container_name: servico_a
    build:
      context: ./Servico_a/
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
      - OTEL_SERVICE_NAME=servico_a
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector

  servico_b:
    container_name: servico_b
    build:
      context: ./Servico_b/
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
      - OTEL_SERVICE_NAME=servico_b
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector

networks:
  comunicacao-ms_my_network:
    driver: bridge
